- name: Installing Catalogue
  hosts: catalogue
  vars:
    component: catalogue
  become: yes
  # tags:
  # - dev
  roles:
  - catalogue

# - name: Installing Catalogue
#   hosts: mongodb
#   become: yes
#   tags:
#   - prod
#   roles:
#   - catalogue